[package]
version = "0.5.2"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
categories = ["web-programming"]
description = "Internal code generation crate for juniper-from-schema"
documentation = "https://docs.rs/juniper-from-schema-proc-macro"
edition = "2018"
homepage = "https://github.com/davidpdrsn/juniper-from-schema"
keywords = ["web", "graphql", "juniper"]
license = "MIT"
name = "juniper-from-schema-code-gen"
readme = "README.md"
repository = "https://github.com/davidpdrsn/juniper-from-schema.git"

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
graphql-parser = "0.3"
proc-macro2 = "1"
heck = "0.3"
colored = "1.8"

[dev_dependencies]
version-sync = "0.8"

[features]
no_validate_snake_case = []
